services:
  - type: web
    name: ecommerce-backend
    env: python
    rootDir: backend
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      alembic upgrade head
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 4 -t 120 main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: shopeasyfrontend.netlify.app
      - key: PIP_NO_CACHE_DIR
        value: 'true'

databases:
  - name: ecommerce-db
    databaseName: ecommercedb
    user: ecomuser
    plan: free
